"""JavaScript target: the C++ library compiled to WebAssembly with Emscripten.

Follows the pattern of sys-bio/libantimonyjs - the existing C++ libraries are
linked with emcc into one self-contained <name>.js (WebAssembly embedded:
-sMODULARIZE=1 -sSINGLE_FILE=1, memory growth on, C++ exceptions on, -Oz), whose
entry points are a flat C API exported through cwrap and wrapped by a small
hand-written JavaScript file - rather than binding every generated class one
by one. The API is strings in, strings out, with JSON as the string format,
since SED2 documents are JSON already (see templates/js/src/api.cpp for the
function list and result shapes).

This target is built ON the C++ target: generated/js/CMakeLists.txt
add_subdirectory()s ../cpp and links its <ns>::<ns> library, so generate.py
always generates cpp whenever it generates js. Like the other targets, what
is hand-written lives under templates/js/ (copied here, never edited in the
output) and everything that depends on the spec or the command line is
generated by this module:

  <out>/js/
    CMakeLists.txt         generated  Emscripten build (emcmake cmake -S . -B build)
    src/generated_api.cpp  generated  library version, document version, class names
    src/api.cpp            template   the fixed entry points (templates/js/src/api.cpp)
    index.js               template   JS wrapper (templates/js/index.js)
    index.d.ts             generated  TypeScript declarations (class-name union from the spec)
    package.json           generated  npm metadata (name, version from VERSION.txt)
    README.md              generated  usage
    test/fixtures.test.js  template   fixture suite run under Node (templates/js/tests/)

The built module itself (<ns>.js) is a build product: CI builds it and packs
it, with index.js, index.d.ts and README.md, into the npm tarball.
"""
import json
import os

from .spec import SpecModel
from .version import check_version, library_version

# Every function the module exports. Must agree with templates/js/index.js's
# FUNCTIONS list; checked at generate time (see _check_template_agreement).
API_FUNCTIONS = [
    "sed2_library_version",
    "sed2_document_version",
    "sed2_class_names",
    "sed2_direct_only_keys",
    "sed2_rule_catalog",
    "sed2_validate_document",
    "sed2_validate_object",
    "sed2_normalize_document",
    "sed2_check_math",
]

# Functions defined by the generated half (src/generated_api.cpp); the rest
# are defined by templates/js/src/api.cpp.
_GENERATED_FUNCTIONS = ["sed2_library_version", "sed2_document_version", "sed2_class_names"]

_RUNTIME_METHODS = ["cwrap", "ccall", "UTF8ToString", "stringToUTF8", "lengthBytesUTF8"]


def _repo_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _template(*parts: str) -> str:
    with open(os.path.join(_repo_root(), "templates", "js", *parts)) as f:
        return f.read()


def _c_lit(s: str) -> str:
    """A C++ string literal for s (ASCII only: json.dumps escapes the rest)."""
    return json.dumps(s)


def _check_template_agreement() -> None:
    """The exported-function list is stated in three places (here, api.cpp +
    generated_api.cpp's definitions, index.js's FUNCTIONS); fail the run if
    they drift apart rather than ship a module the wrapper can't use."""
    api = _template("src", "api.cpp")
    wrapper = _template("index.js")
    for name in API_FUNCTIONS:
        if name not in wrapper:
            raise RuntimeError(f"templates/js/index.js does not mention {name}")
        if name not in _GENERATED_FUNCTIONS and f"EMSCRIPTEN_KEEPALIVE const char* {name}(" not in api:
            raise RuntimeError(f"templates/js/src/api.cpp does not define {name}")
    for name in _GENERATED_FUNCTIONS:
        if name not in API_FUNCTIONS:
            raise RuntimeError(f"{name} is generated but not exported")


def _replace_ns(text: str, ns: str) -> str:
    return text.replace("sed2test", ns)


def _generated_api_cpp(model: SpecModel, version: str) -> str:
    classes = sorted(model.generatable_classes())
    doc_version = model.document_version or ""
    return f'''// Generated half of the JavaScript API (see templates/js/src/api.cpp for the
// fixed half): the entry points whose values come from the spec or from
// VERSION.txt. GENERATED - do not hand-edit; regenerate via
// generator/generate.py.
#include <emscripten.h>

extern "C" {{

/// Library version (VERSION.txt at generate time).
EMSCRIPTEN_KEEPALIVE const char* sed2_library_version() {{ return {_c_lit(version)}; }}

/// Newest SED2 document-format version this library knows.
EMSCRIPTEN_KEEPALIVE const char* sed2_document_version() {{ return {_c_lit(doc_version)}; }}

/// JSON array of every generated class name.
EMSCRIPTEN_KEEPALIVE const char* sed2_class_names() {{ return {_c_lit(json.dumps(classes, separators=(",", ":")))}; }}

}}  // extern "C"
'''


def _cmake_lists(ns: str, version: str, cpp_rel: str) -> str:
    exported = ",".join("_" + f for f in API_FUNCTIONS + ["malloc", "free"])
    methods = ",".join(_RUNTIME_METHODS)
    return f'''# Emscripten build of the {ns} C++ library: one self-contained {ns}.js with the
# WebAssembly embedded. GENERATED - do not hand-edit; regenerate via
# generator/generate.py (generator/emit_js.py; the pattern is libantimonyjs's).
#
#   emcmake cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
#   cmake --build build            # -> build/{ns}.js
#
# The C++ library is pulled in from ../cpp (add_subdirectory, so its fixture
# test target stays off); its own FetchContent dependencies (jsoncons, the
# ANTLR4 C++ runtime) are built for WebAssembly along with it.
cmake_minimum_required(VERSION 3.16)
project({ns}_js VERSION {version} LANGUAGES CXX)

if(NOT EMSCRIPTEN)
  message(FATAL_ERROR "Build this project with Emscripten: emcmake cmake -S . -B build")
endif()

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
set(CMAKE_CXX_FLAGS_RELEASE "-Oz -DNDEBUG")

# The C++ library, jsoncons and the ANTLR runtime all use C++ exceptions, so
# they are enabled for every target, including the FetchContent'd ones.
add_compile_options(-fexceptions)
add_link_options(-fexceptions)

add_subdirectory("${{CMAKE_CURRENT_SOURCE_DIR}}/{cpp_rel}" cpp)

# The target is {ns}_js because {ns} is already the C++ library's own target.
add_executable({ns}_js src/api.cpp src/generated_api.cpp)
target_link_libraries({ns}_js PRIVATE {ns}::{ns})
set_target_properties({ns}_js PROPERTIES OUTPUT_NAME {ns} SUFFIX ".js")
target_link_options({ns}_js PRIVATE
  -sDISABLE_EXCEPTION_CATCHING=0
  -sMODULARIZE=1
  -sSINGLE_FILE=1
  -sEXPORT_NAME={ns}
  -sALLOW_MEMORY_GROWTH=1
  -sEXPORTED_FUNCTIONS={exported}
  -sEXPORTED_RUNTIME_METHODS={methods}
)
'''


def _index_d_ts(model: SpecModel) -> str:
    classes = sorted(model.generatable_classes())
    union = " | ".join(json.dumps(c) for c in classes) if classes else "never"
    return f'''// TypeScript declarations for the JavaScript build. GENERATED - do not
// hand-edit; regenerate via generator/generate.py.

/** Name of a generated SED2 class. */
export type ClassName = {union};

export interface Problem {{
  ruleId: string;
  severity: string;
  rule: string;
  message: string;
  location: string;
}}

/** ok:false means the input could not be processed at all (e.g. malformed JSON). */
export type ValidateResult = {{ ok: true; problems: Problem[] }} | {{ ok: false; error: string }};

export interface Sed2 {{
  /** Version of this library. */
  version(): string;
  /** Newest SED2 document-format version this library knows (e.g. "v1.0.0"). */
  documentVersion(): string;
  classNames(): ClassName[];
  /** Keys accepted by validateObject(). */
  directOnlyKeys(): string[];
  ruleCatalog(): Record<string, {{ rule: string; message: string; severity: string }}>;
  /** Parse and validate a SED2 document. */
  validate(text: string): ValidateResult;
  /** Validate one direct-only class instance, selected by a key from directOnlyKeys(). */
  validateObject(key: string, text: string): ValidateResult;
  /** Parse a document and write it back out in canonical form. */
  normalize(text: string): {{ ok: true; text: string }} | {{ ok: false; error: string }};
  /** Syntax-check a SED2 math string. */
  checkMath(text: string): {{ ok: true }} | {{ ok: false; error: string }};
}}

/** Wraps an instantiated Emscripten module. */
export function wrap(module: unknown): Sed2;
/** Loads the module (Node) and wraps it; modulePath defaults to the sibling build output. */
export function load(modulePath?: string): Promise<Sed2>;
'''


def _package_json(package: str, ns: str, version: str, description: str) -> str:
    pkg = {
        "name": package,
        "version": version,
        "description": description,
        "main": "index.js",
        "types": "index.d.ts",
        "files": ["index.js", "index.d.ts", f"{ns}.js", "README.md", "LICENSE"],
        "engines": {"node": ">=18"},
        "license": "MIT",
        "keywords": ["sed-ml", "sed2", "simulation", "webassembly"],
    }
    return json.dumps(pkg, indent=2) + "\n"


def _readme(package: str, ns: str, version: str) -> str:
    return f'''# {package} {version}

The {ns} C++ library (reading and validating SED2 documents), compiled to
WebAssembly with Emscripten. One self-contained module: the WebAssembly is
embedded in `{ns}.js`.

    const {{ load }} = require("{package}");

    const sed2 = await load();
    const result = sed2.validate(documentText);
    if (!result.ok) console.error(result.error);          // not parseable
    else result.problems.forEach((p) => console.log(p.ruleId, p.location, p.message));

In a browser, include `{ns}.js` and `index.js` with script tags:

    const sed2 = sed2Wrap(await {ns}());

Methods: `version()`, `documentVersion()`, `classNames()`, `directOnlyKeys()`,
`ruleCatalog()`, `validate(text)`, `validateObject(key, text)`,
`normalize(text)`, `checkMath(text)`. See `index.d.ts`.
'''


def emit_js_package(
    model: SpecModel,
    out_dir: str,
    cpp_namespace: str = "sed2test",
    js_package: str = "libsed2test-js",
    description: str | None = None,
    cpp_relative_dir: str = "../cpp",
    version: str | None = None,
) -> None:
    version = check_version(version, "version") if version is not None else library_version()
    description = description or (
        f"The {cpp_namespace} SED2 library compiled to WebAssembly with Emscripten."
    )
    _check_template_agreement()

    os.makedirs(os.path.join(out_dir, "src"), exist_ok=True)
    os.makedirs(os.path.join(out_dir, "test"), exist_ok=True)

    def write(rel: str, text: str) -> None:
        with open(os.path.join(out_dir, rel), "w") as f:
            f.write(text)

    write("CMakeLists.txt", _cmake_lists(cpp_namespace, version, cpp_relative_dir))
    write(os.path.join("src", "generated_api.cpp"), _generated_api_cpp(model, version))
    write(os.path.join("src", "api.cpp"), _replace_ns(_template("src", "api.cpp"), cpp_namespace))
    write("index.js", _replace_ns(_template("index.js"), cpp_namespace))
    write("index.d.ts", _index_d_ts(model))
    write("package.json", _package_json(js_package, cpp_namespace, version, description))
    write("README.md", _readme(js_package, cpp_namespace, version))
    write(os.path.join("test", "fixtures.test.js"), _template("tests", "fixtures.test.js"))
