#pragma once

#include <string>

namespace sed2 {

enum class TokenType {
    Number,      // 1, 1.3, .5, 1e-3
    Reference,   // #tasks:sim1.model['S1']
    Identifier,  // pi, sin, x
    Operator,    // + - * / ^
    LParen,
    RParen,
    Comma,
    End,
    Error,  // an unrecognized character, or a '#' that isn't a valid reference
};

struct Token {
    TokenType type = TokenType::End;
    std::string text;          // raw text for Identifier / Operator / Reference / Error
    double numberValue = 0.0;  // populated for Number
};

// Tokenizes an infix SED2 math expression. Hand-written rather than
// generated by flex (see Design.md's note that nlohmann::json was chosen
// partly for MSVC-friendliness - the same reasoning rules out a
// flex/bison toolchain dependency here). The one lexical subtlety this
// exists to get right is telling a decimal number (1.3) apart from a
// reference's dot-accessor (#a:b.c) - the two share '.' but a dot
// accessor never appears outside a '#'-led span, so the lexer commits to
// "reference" the moment it sees '#' and scans the whole span in one go
// via AttributeTypes::scanReferenceLength.
class Lexer {
public:
    explicit Lexer(std::string input);

    // Returns the next token and advances past it. Returns TokenType::End,
    // repeatedly, once the input is exhausted.
    Token next();

    // Returns the next token without advancing.
    const Token& peek();

private:
    Token lexOne();
    Token lexNumber();
    Token lexReference();
    Token lexIdentifier();
    void skipWhitespace();

    std::string input_;
    std::size_t pos_ = 0;
    bool hasPeeked_ = false;
    Token peeked_;
};

}  // namespace sed2
